ecom/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecom.Data.Services;
using ecom.Data.Cart;
using ecom.Data.ViewModels;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;
    
namespace ecom.Controllers
{
    [Route("admin")]
    [Authorize(Roles = "Admin")]
    public class AdminOrdersController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly IOrdersService _ordersService;
        
        public AdminOrdersController(IBooksService booksService, IOrdersService ordersService)
        {
            _booksService = booksService;
            _ordersService = ordersService;
            Thread.CurrentThread.CurrentCulture = new CultureInfo("lk-LK");
        }


        [Route("orders")]
        public async Task<IActionResult> Orders()
        {
            var orders = await  _ordersService.GetOrdersAsync();
            return View("orders", orders);
        }


    }
}

ecom/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecom.Data.Services;
using ecom.Data.Cart;
using ecom.Data.ViewModels;
using Microsoft.AspNetCore.Identity;
using ecom.Models;
using ecom.Data.Static;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using ecom.Data;
using Microsoft.EntityFrameworkCore;

namespace ecom.Controllers
{
    [Route("admin")]
    [Authorize(Roles = "Admin")]
     public class AdminUserController : Controller
     {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly AppDbContext _context;

         public AdminUserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, AppDbContext context)
         {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
         }
        [Route("users")]
         public async Task<IActionResult> Users()
         {
            var users =await _context.Users.ToListAsync();
            return View("index", users);
         }
     }
}

ecom/Views/Shared/Admin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ecom</title>

    <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700" rel="stylesheet">
    <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css" rel="stylesheet">
    
    <link rel="shortcut icon" href="~/ebook.ico">
	  <link rel="apple-touch-icon" href="~/ebook.ico">

    <link rel="stylesheet" type="text/css" href="~/theme-assets/css/vendors.css">
    <link rel="stylesheet" type="text/css" href="~/theme-assets/vendors/css/charts/chartist.css">
    <link rel="stylesheet" type="text/css" href="~/theme-assets/css/app-lite.css">
    <link rel="stylesheet" type="text/css" href="~/theme-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="~/theme-assets/css/core/colors/palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="~/theme-assets/css/pages/dashboard-ecommerce.css">

    <style>
        body::-webkit-scrollbar {
        width: 8px;
        }

        body::-webkit-scrollbar-track {
        background: #262d47;
        }

        body::-webkit-scrollbar-thumb {
        background-color: #4751c2;
        border-radius: 20px; 
        border: 3px solid #262d47;
        }
    </style>
</head>
<body class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar" data-open="click" data-menu="vertical-menu" data-color="bg-chartbg" data-col="2-columns">
 @* <body class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar" data-open="click" data-menu="vertical-menu" data-color="bg-gradient-x-purple-blue" data-col="2-columns"> *@
    <!-- fixed-top-->
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light">
      <div class="navbar-wrapper">
        <div class="navbar-container content">
          <div class="collapse navbar-collapse show" id="navbar-mobile">
            <div class="nav navbar-nav mr-auto float-left">
                <h3 class="content-header-title" style="color: #fff;">&nbsp; &nbsp;Admin - @ViewData["Head"]</h3>
              @* <li class="nav-item d-block d-md-none"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
              <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
              <li class="nav-item dropdown navbar-search"><a class="nav-link dropdown-toggle hide" data-toggle="dropdown" href="#"><i class="ficon ft-search"></i></a>
                <ul class="dropdown-menu">
                  <li class="arrow_box">
                    <form>
                      <div class="input-group search-box">
                        <div class="position-relative has-icon-right full-width">
                          <input class="form-control" id="search" type="text" placeholder="Search here...">
                          <div class="form-control-position navbar-search-close"><i class="ft-x">   </i></div>
                        </div>
                      </div>
                    </form>
                  </li>
                </ul>
              </li> *@
            </div>
            
            <ul class="nav navbar-nav float-right">
              
              <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">             <span class="avatar avatar-online"><img src="https://ui-avatars.com/api/?name=Ebook+Admin" alt="avatar"><i></i></span></a>
                <div class="dropdown-menu dropdown-menu-right">
                  <div class="arrow_box_right"><a class="dropdown-item" href="#"><span class="avatar avatar-online"><img src="https://ui-avatars.com/api/?name=Ebook+Admin" alt="avatar"><span class="user-name text-bold-700 ml-1">Admin</span></span></a>
                    
                    
                    <div class="dropdown-divider">

                    </div><a class="dropdown-item" asp-controller="Account" asp-action="logout"><i class="ft-power"></i> Logout</a>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
        </div>
      </div>
    </nav>



<partial name="~/Views/Shared/Admin/_Sidebar.cshtml" />
 

    <div class="app-content content">
      <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        @* <div class="content-header row">
          <div class="content-header-left col-md-4 col-12 mb-2">
            <h3 class="content-header-title">@ViewData["Title"]</h3>
          </div>
          <div class="content-header-right col-md-8 col-12">
            <div class="breadcrumbs-top float-md-right">
              <div class="breadcrumb-wrapper mr-1">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Admin</a>
                  </li>
                  <li class="breadcrumb-item active">@ViewData["Title"]
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div> *@

        <div class="content-body">
            @RenderBody()
        </div>


      </div>
    </div>

    <footer class="footer footer-static footer-light navbar-border navbar-shadow">
      <div class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">2022  &copy; Copyright 
          
          </span>
        
      </div>
    </footer>



    
    <script src="~/theme-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
    
    <script src="~/theme-assets/vendors/js/charts/chartist.min.js" type="text/javascript"></script>
    
    <script src="~/theme-assets/js/core/app-menu-lite.js" type="text/javascript"></script>
    <script src="~/theme-assets/js/core/app-lite.js" type="text/javascript"></script>
    
    <script src="~/theme-assets/js/scripts/pages/dashboard-lite.js" type="text/javascript"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ecom/Views/Shared/Admin/_Sidebar.cshtml
 <!-- ////////////////////////////////////////////////////////////////////////////-->


    <div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true" data-img="/theme-assets/images/backgrounds/02.jpg">
      <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">       
          <li class="nav-item mr-auto"><a class="navbar-brand" href="~/"><img class="brand-logo" alt="Chameleon admin logo" src="/theme-assets/images/logo/eblogo.png"/>
              <h3 class="brand-text">E-BooK LTD</h3></a></li>
          <li class="nav-item d-md-none"><a class="nav-link close-navbar"><i class="ft-x"></i></a></li>
        </ul>
      </div>
      <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
          <li class='@ViewData["Dashboard"]'><a href='@Url.RouteUrl("dashboard")'><i class="ft-home"></i><span class="menu-title" data-i18n="">Dashboard</span></a>
          </li>
          <li class='@ViewData["Writers"] nav-item'><a href='@Url.RouteUrl("writers")'><i class="la la-pencil"></i><span class="menu-title" data-i18n="">Writers</span></a>
          </li>
          <li class='@ViewData["Publishers"] nav-item'><a href='@Url.RouteUrl("publisher")'><i class="la la-laptop"></i><span class="menu-title" data-i18n="">Publishers</span></a>
          </li>
          <li class='@ViewData["Books"] nav-item'><a href='@Url.RouteUrl("books")'><i class="la la-book"></i><span class="menu-title" data-i18n="">Books</span></a>
          </li>
          <li class='@ViewData["Orders"] nav-item'><a asp-action="Orders" asp-controller="AdminOrders"><i class="la la-cart-plus"></i><span class="menu-title" data-i18n="">Orders</span></a>
          </li>
          <li class='@ViewData["Users"] nav-item'><a asp-action="Users" asp-controller="AdminUser"><i class="la la-user"></i><span class="menu-title" data-i18n="">Users</span></a>
          </li>

@*           
          <li class=" nav-item"><a href="buttons.html"><i class="ft-box"></i><span class="menu-title" data-i18n="">Buttons</span></a>
          </li>
          <li class=" nav-item"><a href="typography.html"><i class="ft-bold"></i><span class="menu-title" data-i18n="">Typography</span></a>
          </li>
          <li class=" nav-item"><a href="tables.html"><i class="ft-credit-card"></i><span class="menu-title" data-i18n="">Tables</span></a>
          </li>
          <li class=" nav-item"><a href="form-elements.html"><i class="ft-layout"></i><span class="menu-title" data-i18n="">Form Elements</span></a>
          </li>
          <li class=" nav-item"><a href="https://themeselection.com/demo/chameleon-admin-template/documentation"><i class="ft-book"></i><span class="menu-title" data-i18n="">Documentation</span></a>
          </li> *@
          
        </ul>


      </div>
      
      <div class="navigation-background"></div>
    </div>