ecom/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace ecom.Controllers
{
    [Route("admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        [Route("dashboard", Name = "dashboard")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

ecom/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecom.Data.Services;
using ecom.Data.Cart;
using ecom.Data.ViewModels;
using Microsoft.AspNetCore.Identity;
using ecom.Models;
using ecom.Data.Static;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using ecom.Data;

namespace ecom.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly AppDbContext _context;

        public OrdersController(IBooksService booksService, ShoppingCart shoppingCart, IOrdersService ordersService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, AppDbContext context)
        {
            _booksService = booksService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [Route("cart")]
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                shoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View("cart", response);
        }
        [Route("/addtoshoppingcart")]
        public async Task<RedirectToActionResult> AddToShoppingCart(int id, int? qty)
        {
            var item = await _booksService.GetBookByIdAsync(id);
            if(item != null)
            {   if(qty == null){
                    _shoppingCart.AddItemToCart(item);
                }
                else{
                    if(qty == 1)
                    {
                    _shoppingCart.AddItemToCart(item);
                    }
                    else{
                        int i;
                        for(i =1; i <= qty; i++)
                        {
                            _shoppingCart.AddItemToCart(item);
                        }
                    }
                }
            }
            return RedirectToAction(nameof(Index));

        }
        [Route("removecartitems/")]
        public async Task<RedirectToActionResult> RemoveFromShoppingCart(int id, int? qty)
        {
            var item = await _booksService.GetBookByIdAsync(id);
            if(item != null)
            {   
                 if(qty != null)
                {
                    int i;
                    for(i =1; i <= qty; i++)
                    {
                        _shoppingCart.RemoveItemFromCart(item);
                    }
                }
                else{
                     _shoppingCart.RemoveItemFromCart(item);
                }
            }
            return RedirectToAction(nameof(Index));

        }
        [Route("checkout")]
        public IActionResult Checkout()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            if(items.Count == 0) return RedirectToAction("Shop", "Home");
            _shoppingCart.ShoppingCartItems = items;

            var cartdata = new ShoppingCartVM()
            {
                shoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            ViewBag.cartdata = cartdata;
            if(User.Identity.IsAuthenticated)
            {
                if(User.IsInRole("User"))
                {
                    var userId = _userManager.GetUserId(User);
                    var user = _context.Users.Where(n => n.Id == userId).FirstOrDefault();
                    var res = new LoggedOrderVM()
                    {
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Address = user.Address,
                        Apartment = user.Apartment,
                        District = user.District,
                        Postcode = user.Postcode,
                    };
                    ViewBag.atribute = "disabled readonly";
                    return View("checkoutLogged", res);
                }
            }
            var response = new RegisterVm();
            return View("checkout", response);
        }

        [HttpPost("order/checkout")]
        public async Task<IActionResult> OrderSave(RegisterVm registerVm)
        {
            if(!ModelState.IsValid) 
            {
                var items = _shoppingCart.GetShoppingCartItems();
                //if(items.Count == 0) return RedirectToAction("Shop", "Home");
                _shoppingCart.ShoppingCartItems = items;

                var cartdata = new ShoppingCartVM()
                {
                    shoppingCart = _shoppingCart,
                    ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
                };
                ViewBag.cartdata = cartdata;

                return View("Checkout", registerVm);
            }
            
            var user = await _userManager.FindByEmailAsync(registerVm.EmailAddress);
            //return RedirectToAction(nameof(Index));
            if(user != null)
            {
                TempData["Error"] = "This email address is already in use.";
                return RedirectToAction(nameof(Checkout), registerVm);
            }
            var newuser = new ApplicationUser()
            {
                FirstName = registerVm.FirstName,
                LastName = registerVm.LastName,
                Address = registerVm.Address,
                Apartment = registerVm.Apartment,
                District = registerVm.District,
                Postcode = registerVm.Postcode,
                PhoneNumber = registerVm.PhoneNumber,
                Email = registerVm.EmailAddress,
                UserName = registerVm.EmailAddress
            };

            var newUserResponse = await _userManager.CreateAsync(newuser, registerVm.Password);
            
            if(newUserResponse.Succeeded)
            {
                var reguser = await _userManager.FindByEmailAsync(registerVm.EmailAddress);
                await _userManager.AddToRoleAsync(newuser, UserRoles.User);

                
                var result = await _signInManager.PasswordSignInAsync(reguser, registerVm.Password, false, false);

                var cartitems = _shoppingCart.GetShoppingCartItems();
                string userId = newuser.Id;
                string userEmailAddress = newuser.Email;
                
                var order = await _ordersService.StoreOrderAsync(cartitems, userId, userEmailAddress, newuser);



                await _shoppingCart.ClearShoppingCartAsync();
                
                return RedirectToAction(nameof(OrderConfirmed), new { orderId = order.Id });
            
            }
            else{
                var items = _shoppingCart.GetShoppingCartItems();
                //if(items.Count == 0) return RedirectToAction("Shop", "Home");
                _shoppingCart.ShoppingCartItems = items;

                var cartdata = new ShoppingCartVM()
                {
                    shoppingCart = _shoppingCart,
                    ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
                };
                ViewBag.cartdata = cartdata;
                return View("Checkout", registerVm);
            }
            
            
        }


        [HttpPost("order/checkout/user")]
        [Authorize]
        public async Task<IActionResult> OrderSaveUser(LoggedOrderVM loggedOrderVM)
        {
            if(!ModelState.IsValid) 
            {
                var items = _shoppingCart.GetShoppingCartItems();
                if(items.Count == 0) return RedirectToAction("Shop", "Home");
                _shoppingCart.ShoppingCartItems = items;

                var cartdata = new ShoppingCartVM()
                {
                    shoppingCart = _shoppingCart,
                    ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
                };
                ViewBag.cartdata = cartdata;

                return View("checkoutLogged", loggedOrderVM);
            }
            var email = _userManager.GetUserName(User);
            var user = await _userManager.FindByEmailAsync(email);
            
            //return RedirectToAction(nameof(Index));
            if(user == null)
            {
                TempData["Error"] = "Something wrong! Please try sign out and sign in again.";
                return RedirectToAction(nameof(Checkout), loggedOrderVM);
            }
            
            user.Address = loggedOrderVM.Address;
            user.Apartment = loggedOrderVM.Apartment;
            user.District = loggedOrderVM.District;
            user.Postcode = loggedOrderVM.Postcode;

            var cartitems = _shoppingCart.GetShoppingCartItems();
            string userId = _userManager.GetUserId(User);
            string userEmailAddress = email;
            
            var order = await _ordersService.StoreOrderAsync(cartitems, userId, userEmailAddress, user);
            //var address = await _ordersService.SaveAddress(order.Id, user);
            await _shoppingCart.ClearShoppingCartAsync();
            
            return RedirectToAction(nameof(OrderConfirmed), new { orderId = order.Id });



        }

        [Route("order/invoice")]
        [Authorize]
        public async Task<IActionResult> OrderConfirmed(int? orderid)
        {
            if(orderid == null) return View("NotFound");
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

ecom/Views/Shared/Front/Header.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> UserManager;
<header id="wn__header" class="header__area header__absolute sticky__header">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-6 col-sm-6 col-6 col-lg-2">
						<div class="logo">
							<a asp-route="Home">
								<img src="~/images/logo/ad_logo.png" alt="logo images">
							</a>
						</div>
					</div>
					<div class="col-lg-8 d-none d-lg-block">
						<nav class="mainmenu__nav">
							<ul class="meninmenu d-flex justify-content-start">
								<li class="drop with--one--item"><a asp-route="Home">Home</a>
								</li>
								<li class="drop"><a asp-route="Shop">All Product</a>
								</li>
								@* <li class="drop"><a href="shop-grid.html">Books</a>
									<div class="megamenu mega03">
										<ul class="item item03">
											<li class="title">Categories</li>
											<li><a href="shop-grid.html">Biography </a></li>
											<li><a href="shop-grid.html">Business </a></li>
											<li><a href="shop-grid.html">Cookbooks </a></li>
											<li><a href="shop-grid.html">Health & Fitness </a></li>
											<li><a href="shop-grid.html">History </a></li>
										</ul>
										<ul class="item item03">
											<li class="title">Customer Favourite</li>
											<li><a href="shop-grid.html">Mystery</a></li>
											<li><a href="shop-grid.html">Religion & Inspiration</a></li>
											<li><a href="shop-grid.html">Romance</a></li>
											<li><a href="shop-grid.html">Fiction/Fantasy</a></li>
											<li><a href="shop-grid.html">Sleeveless</a></li>
										</ul>
										<ul class="item item03">
											<li class="title">Collections</li>
											<li><a href="shop-grid.html">Science </a></li>
											<li><a href="shop-grid.html">Fiction/Fantasy</a></li>
											<li><a href="shop-grid.html">Self-Improvemen</a></li>
											<li><a href="shop-grid.html">Home & Garden</a></li>
											<li><a href="shop-grid.html">Humor Books</a></li>
										</ul>
									</div>
								</li> *@
								
								<li><a asp-controller="Home" asp-action="aboutus">About Us</a></li>
								<li><a asp-controller="Home" asp-action="contactus">Contact Us</a></li>
							</ul>
						</nav>
					</div>
					<div class="col-md-6 col-sm-6 col-6 col-lg-2">
						<ul class="header__sidebar__right d-flex justify-content-end align-items-center">
							@if(User.Identity.IsAuthenticated)
							{
								@* <li style="margin-right: 20px; color: #2f5a85;">Hello @UserManager.GetUserName(User)</li> *@
							}
							
							<li class="shop_search" style="margin-right: 20px;"><a class="search__active" href="#"></a></li>
							@* <li class="wishlist"><a href="#"></a></li> *@
							<li class="shopcart"><a asp-controller="Orders" asp-action="Index"><span class="product_qun"> @await Component.InvokeAsync("ShoppingCartSummary") </span></a>
								
							</li>
							<li class="setting__bar__icon"><a class="setting__active" href="#"> </a>
								<div class="searchbar__content setting__block">
									<div class="content-inner">
										
										<div class="switcher-currency">
											<strong class="label switcher-label">
												<span>My Account</span>
											</strong>
											<div class="switcher-options">
												<div class="switcher-currency-trigger">
													<div class="setting__menu">
														@* <span><a href="#">Compare Product</a></span> *@
														@if(User.Identity.IsAuthenticated)
														{
															@if (User.IsInRole("Admin"))
															{
																<span><a asp-action="Index" asp-controller="Dashboard">Admin Dashboard</a></span>
																<span><a onclick="document.getElementById('formLogout').submit();">Sign Out</a></span>
																<form id="formLogout" asp-controller="Account" asp-action="Logout" method="post"></form>
															}
															else{
															@* <span><a href="#">My Account</a></span> *@
															<span><a asp-action="MyOrders" asp-controller="Orders">My Orders</a></span>
															<span><a onclick="document.getElementById('formLogout').submit();">Sign Out</a></span>
															<form id="formLogout" asp-controller="Account" asp-action="Logout" method="post"></form>
																
															}
														}
														else{
															<span><a asp-controller="Account" asp-action="Login">Sign In</a></span>

															@* <span><a href="#">Create An Account</a></span> *@
														}
														

														
													</div>
												</div>
											</div>
										</div>


									</div>
								</div>
							</li>
						</ul>
					</div>
				</div>
				<!-- Start Mobile Menu -->
				<div class="row d-none">
					<div class="col-lg-12 d-none">
						<nav class="mobilemenu__nav">
							<ul class="meninmenu">
								<li><a asp-route="Home">Home</a></li>
								
								<li><a asp-route="Shop">Shop</a></li>
								
								<li><a href="contact.html">Contact</a></li>
							</ul>
						</nav>
					</div>
				</div>
				<!-- End Mobile Menu -->
	            <div class="mobile-menu d-block d-lg-none">
	            </div>
	            <!-- Mobile Menu -->	
			</div>		
		</header>
		<!-- //Header -->
		

ecom/Views/Shared/Front/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EBoook</title>

	<meta name="title" content='@ViewData["Title"] - EBOOK.LK' />
	<meta name="keywords" content="EBOOK, ebook, online book, madhusanka alwis, alwis, m alwis " />
	<meta name="description" content='@ViewData["des"]' />
	<meta property="og:url" content="@Context.Request.GetEncodedUrl()" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content='@ViewData["Title"]' />
	<meta property="og:description" content='@ViewData["des"]' />
	<meta property="og:image" content='@ViewData["metaimg"]' />



	<link rel="shortcut icon" href="~/ebook.ico">
	<link rel="apple-touch-icon" href="~/ebook.ico">
	
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet"> 


	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/plugins.css">
	<link rel="stylesheet" href="~/style.css">


   <link rel="stylesheet" href="~/css/custom.css">
	    <style>
        body::-webkit-scrollbar {
        width: 3px;
        }

        body::-webkit-scrollbar-track {
        background: #f6f6f6;
        }

        body::-webkit-scrollbar-thumb {
        background-color: #2f5a85;
        border-radius: 10px; 
        @* border: 1px solid #fff; *@
        }
    </style>

	<script src="~/js/vendor/modernizr-3.5.0.min.js"></script>


</head>
<body>
    <div class="wrapper" id="wrapper">
        <partial name="~/Views/Shared/Front/Header.cshtml" />

		<!-- Start Search Popup -->
		<div class="brown--color box-search-content search_active block-bg close__top">
			<form id="search_mini_form" class="minisearch" method="get" asp-controller="Home" asp-action="Shop">
				<div class="field__search">
					<input type="text" name="search" value='@ViewData["search"]' placeholder="Search entire store here...">
					<div class="action">
						<a onclick="document.getElementById('search_mini_form').submit();"><i class="zmdi zmdi-search"></i></a>
					</div>
				</div>
			</form>
			<div class="close__wrap">
				<span>close</span>
			</div>
		</div>
		<!-- End Search Popup -->


        @RenderBody()

        <!-- Footer Area -->
		<footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
			<div class="footer-static-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="footer__widget footer__menu">
								<div class="ft__logo">
									<a asp-route="Home">
										<img src="~/images/logo/ad_logo.png" alt="logo">
									</a>
									
								</div>
								<div class="footer__content">
									
									<ul class="mainmenu d-flex justify-content-center">
										<li><a asp-route="Home">Home</a></li>
										<li><a asp-route="Shop">All Product</a></li>
										<li><a asp-controller="Home" asp-action="contactus">Contact Us</a></li>
										<li><a asp-controller="Home" asp-action="aboutus">About Us</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright__wrapper">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12">
							<div class="copyright">
								<div class="copy__right__inner text-left">
									<p>Copyright <i class="fa fa-copyright"></i> <a href="#"> | All Rights reserved</a> @*| All Rights Reserved*@</p>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12">
							<div class="payment text-right">
								<img src="~/images/icons/payment.png" alt="" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- //Footer Area -->
    </div>
   
            


  

	<script src="~/js/vendor/jquery-3.2.1.min.js"></script>
	<script src="~/js/popper.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/plugins.js"></script>
	<script src="~/js/active.js"></script>
	


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>